services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qrcodes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/qrcodes  # Connection string for Flask

  web:
    build: ./web
    ports:
      - "80:80"

volumes:
  db_data:  # Named volume for PostgreSQL data persistence