apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-code-backend
  template:
    metadata:
      labels:
        app: qr-code-backend
    spec:
      containers:
      - name: qr-code-backend
        image: your-dockerhub-username/qr-code-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
 value: password
        - name: POSTGRES_DB
          value: qrcodes
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: qr-code-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: qr-code-backend
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres